Repository CSC207-UofT/course-project-generic-name-1, pull requests merged in 2021-12, with the labels that each got.

#66 login and logout
  Uni_life_tracker/app/src/main/java/com/generic/plannr/ExpensesActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/LoginActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/MainPageActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/SchoolActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/SettingsActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/SignUpActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/WelcomeActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/WelcomeLoginSignupActivity.java
  Uni_life_tracker/app/src/main/res/drawable/ic_logout.xml
  Uni_life_tracker/app/src/main/res/layout/activity_add_event.xml
  Uni_life_tracker/app/src/main/res/layout/activity_expenses.xml
  Uni_life_tracker/app/src/main/res/layout/activity_login_page.xml
  Uni_life_tracker/app/src/main/res/layout/activity_main_page.xml
  Uni_life_tracker/app/src/main/res/layout/activity_school.xml
  Uni_life_tracker/app/src/main/res/layout/activity_settings.xml
  Uni_life_tracker/app/src/main/res/layout/activity_signup.xml
  Uni_life_tracker/app/src/main/res/layout/activity_welcome_login_signup.xml
  Uni_life_tracker/app/src/main/res/layout/main_nav.xml
  Uni_life_tracker/app/src/main/res/values/strings.xml
  Uni_life_tracker/app/src/main/res/values/themes.xml
Labels: enhancement

#71 school event list
  Uni_life_tracker/app/src/main/java/com/generic/plannr/CalendarAdapter.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/SchoolActivity.java
  Uni_life_tracker/app/src/main/res/layout/activity_school.xml
Labels: enhancement

#70 Expenses backend connection
  Uni_life_tracker/app/src/main/java/com/generic/plannr/AddExpensesActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/ExpensesActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/ExpensesLandingActivity.java
  Uni_life_tracker/app/src/main/res/layout/activity_add_expenses.xml
  Uni_life_tracker/app/src/main/res/layout/list_expenses.xml
Labels: documentation, enhancement

#74 User and user manager fixes
  Uni_life_tracker/app/src/main/java/com/generic/plannr/Entities/User.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/UseCases/UserManager.java
Labels: bug, enhancement

#77 Welcome name ToDos
  Uni_life_tracker/app/src/main/java/com/generic/plannr/AddEventActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/MainPageActivity.java
  Uni_life_tracker/app/src/main/res/layout/activity_add_event.xml
  Uni_life_tracker/app/src/main/res/layout/activity_main_page.xml
  Uni_life_tracker/app/src/main/res/values/strings.xml
Labels: enhancement

#79 Add income
  Uni_life_tracker/app/src/main/java/com/generic/plannr/ExpensesActivity.java
  Uni_life_tracker/app/src/main/res/layout/activity_expenses.xml
  Uni_life_tracker/app/src/main/res/values/ids.xml
  Uni_life_tracker/app/src/main/res/values/strings.xml
Labels: help wanted

#86 reformat add event
  Uni_life_tracker/app/src/main/java/com/generic/plannr/AddEventActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/ListEvents.java
  Uni_life_tracker/app/src/main/java/com/generic/plannr/MainActivity.java
  Uni_life_tracker/app/src/main/res/drawable/rounded_edge_background.xml
  Uni_life_tracker/app/src/main/res/layout/activity_add_event.xml
  Uni_life_tracker/app/src/main/res/layout/activity_main.xml
  Uni_life_tracker/app/src/main/res/layout/list_events.xml
  Uni_life_tracker/app/src/main/res/layout/list_expenses.xml
  Uni_life_tracker/app/src/main/res/layout/popup_view_event.xml
  Uni_life_tracker/app/src/main/res/values/strings.xml
Labels: enhancement

#103 Final Design Document
  phase2/design_document.md
  phase2/img_3.png
Labels: documentation
