Repository CSC207-UofT/course-project-generic-name-1, pull requests merged in 2021-11, with the labels that each got.

#8 test-pull-request
  src/test/java/ExpensesManagerTest.java
Labels: documentation

#23 Settings_page
  Uni_life_tracker/app/src/main/AndroidManifest.xml
  Uni_life_tracker/app/src/main/java/com/generic/ult/MainActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/Settings_page.java
  Uni_life_tracker/app/src/main/left_arrow-playstore.png
  Uni_life_tracker/app/src/main/res/drawable/left_arrow.xml
  Uni_life_tracker/app/src/main/res/font/roboto_mono_bold.xml
  Uni_life_tracker/app/src/main/res/font/roboto_mono_light.xml
  Uni_life_tracker/app/src/main/res/layout/activity_main.xml
  Uni_life_tracker/app/src/main/res/layout/activity_settings_page.xml
  Uni_life_tracker/app/src/main/res/mipmap-anydpi-v26/left_arrow_round.xml
  Uni_life_tracker/app/src/main/res/mipmap-hdpi/left_arrow.png
  Uni_life_tracker/app/src/main/res/mipmap-hdpi/left_arrow_background.png
  Uni_life_tracker/app/src/main/res/mipmap-hdpi/left_arrow_foreground.png
  Uni_life_tracker/app/src/main/res/mipmap-hdpi/left_arrow_round.png
  Uni_life_tracker/app/src/main/res/mipmap-mdpi/left_arrow.png
  Uni_life_tracker/app/src/main/res/mipmap-mdpi/left_arrow_background.png
  Uni_life_tracker/app/src/main/res/mipmap-mdpi/left_arrow_foreground.png
  Uni_life_tracker/app/src/main/res/mipmap-mdpi/left_arrow_round.png
  Uni_life_tracker/app/src/main/res/mipmap-xhdpi/left_arrow.png
  Uni_life_tracker/app/src/main/res/mipmap-xhdpi/left_arrow_background.png
  Uni_life_tracker/app/src/main/res/mipmap-xhdpi/left_arrow_foreground.png
  Uni_life_tracker/app/src/main/res/mipmap-xhdpi/left_arrow_round.png
  Uni_life_tracker/app/src/main/res/mipmap-xxhdpi/left_arrow.png
  Uni_life_tracker/app/src/main/res/mipmap-xxhdpi/left_arrow_background.png
  Uni_life_tracker/app/src/main/res/mipmap-xxhdpi/left_arrow_foreground.png
  Uni_life_tracker/app/src/main/res/mipmap-xxhdpi/left_arrow_round.png
  Uni_life_tracker/app/src/main/res/mipmap-xxxhdpi/left_arrow.png
  Uni_life_tracker/app/src/main/res/mipmap-xxxhdpi/left_arrow_background.png
  Uni_life_tracker/app/src/main/res/mipmap-xxxhdpi/left_arrow_foreground.png
  Uni_life_tracker/app/src/main/res/mipmap-xxxhdpi/left_arrow_round.png
  Uni_life_tracker/app/src/main/res/values/font_certs.xml
  Uni_life_tracker/app/src/main/res/values/preloaded_fonts.xml
  Uni_life_tracker/app/src/main/res/values/strings.xml
Labels: enhancement

#17 Expenses_landing and Add_expenses
  Uni_life_tracker/app/src/main/java/Entities/Event.java
  Uni_life_tracker/app/src/main/res/font/roboto_mono_light.xml
Labels: enhancement

#40 fix-manifest-error
  Uni_life_tracker/app/src/main/AndroidManifest.xml
  Uni_life_tracker/app/src/main/res/values/strings.xml
Labels: bug

#44 updated method to match the new changes
  Uni_life_tracker/app/src/main/java/Controllers/EventController.java
Labels: bug

#53 reformat-pages
  Uni_life_tracker/app/src/main/AndroidManifest.xml
  Uni_life_tracker/app/src/main/java/com/generic/ult/AddEventActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/AddExpensesActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/ExpensesActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/ExpensesLandingActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/ExpensesList.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/ListEvents.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/ListExpenses.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/MainPageActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/SchoolActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/SettingsActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/SignUpActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/WelcomeActivity.java
  Uni_life_tracker/app/src/main/res/drawable/ic_done_black.xml
  Uni_life_tracker/app/src/main/res/drawable/ic_plus_black.xml
  Uni_life_tracker/app/src/main/res/layout/activity_add_event.xml
  Uni_life_tracker/app/src/main/res/layout/activity_add_expenses.xml
  Uni_life_tracker/app/src/main/res/layout/activity_expenses.xml
  Uni_life_tracker/app/src/main/res/layout/activity_expenses_list.xml
  Uni_life_tracker/app/src/main/res/layout/activity_main_page.xml
  Uni_life_tracker/app/src/main/res/layout/activity_school.xml
  Uni_life_tracker/app/src/main/res/layout/activity_school_main.xml
  Uni_life_tracker/app/src/main/res/layout/activity_settings.xml
  Uni_life_tracker/app/src/main/res/layout/activity_signup.xml
  Uni_life_tracker/app/src/main/res/layout/activity_welcome.xml
  Uni_life_tracker/app/src/main/res/layout/list_events.xml
  Uni_life_tracker/app/src/main/res/layout/list_expenses.xml
  Uni_life_tracker/app/src/main/res/layout/main_nav.xml
  Uni_life_tracker/app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#56 ErrorFix
  Uni_life_tracker/app/src/main/java/com/generic/ult/MainPageActivity.java
Labels: bug

#61 login-page
  Uni_life_tracker/app/src/main/AndroidManifest.xml
  Uni_life_tracker/app/src/main/java/com/generic/ult/LoginActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/WelcomeActivity.java
  Uni_life_tracker/app/src/main/java/com/generic/ult/WelcomeLoginSignupActivity.java
  Uni_life_tracker/app/src/main/res/layout/activity_login_page.xml
  Uni_life_tracker/app/src/main/res/layout/activity_settings.xml
  Uni_life_tracker/app/src/main/res/layout/activity_welcome_login_signup.xml
  Uni_life_tracker/app/src/main/res/values/strings.xml
Labels: bug, enhancement
